# Generated by Django 4.2.29 on 2026-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
