# Generated by Django 4.2.29 on 2026-04-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_album"),
        ("editor", "0002_image_file_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="projects.album",
            ),
        ),
    ]
